### ISSUE TITLE
deleteWebhook on finalize

### ISSUE THREAD

**Issue by benkio** [apimorphism/telegramium#206]
Playing with Webhook bots I realized that there's no integrated mechanism to remove the webhook as there's for setting it up:

When a webhook bot is created (the `Resource[F, Server]` is built) an embedded `setWebhook` is performed, but there's no `deleteWebhook` on finalize for such Resource.
As a result, when you terminate your program, the webhook is still set up.
As a workaround I launch the polling version of the same bot in order to delete the webhook (I saw it does it)
What do you think about adding the `deleteWebhook` with `onFinalize`?

**Comment by johnspade** [comment]
We had it at some point, but I had to remove it. If you have multiple running instances of your webhook bot (for blue-green deployment, for example) and shutdown one of them, all instances stop receiving updates because `deleteWebhook` was called. It's not nessessary to delete a webhook when you terminate your bot, but if you need it, you can add `onFinalize` with `deleteWebhook` in your code, I think.
